client localhost {
	ipaddr = 127.0.0.1
	secret = testing123 # lab-only password
	nas_type = other
}

client localhost_ipv6 {
	ipv6addr = ::1
	secret = testing123 # lab-only password
}

# BEGIN ANSIBLE MANAGED SWITCH CLIENT
client containerlab_switches {
    ipaddr = 0.0.0.0/0
    secret = Cisco123Secret # lab-only password
    require_message_authenticator = no
}
# END ANSIBLE MANAGED SWITCH CLIENT
